import "@/app/globals.css";
import BackButton from "@/components/ui/backbutton";

export const metadata = {
    title: "Next.js",
    description: "Generated by Next.js",
};

export default function RootLayout({
    children,
}: {
    children: React.ReactNode;
}) {
    return (
        <html lang="en">
            <body className="">
                <BackButton className="absolute z-10 top-2 left-2">
                    {"<"}
                </BackButton>
                {children}
            </body>
        </html>
    );
}
